In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Phân loại văn bản với Gaussian Naive Bayes

In [4]:
import math
import numpy as np

In [7]:
from numpy import loadtxt

# Lấy thông tin dữ liệu train và test từ file csv 
X_train = loadtxt('/content/drive/MyDrive/HM/dataIntXTrain.csv', delimiter=',')
X_test = loadtxt('/content/drive/MyDrive/HM/dataIntXTest.csv', delimiter=',')
y_train = loadtxt('/content/drive/MyDrive/HM/dataIntYTrain.csv', delimiter=',')
y_test = loadtxt('/content/drive/MyDrive/HM/dataIntYTest.csv', delimiter=',')


In [8]:
# tính toán giá trị trung bình của mỗi thuộc tính 
def mean(numbers): 
    return sum(numbers) / float(len(numbers))

# tính độ lệch chuẩn cho từng thuộc tính 
def standard_deviation(numbers):
    avg = mean(numbers)
    variance = sum([pow(x - avg, 2) for x in numbers]) / float(len(numbers) - 1)

    return math.sqrt(variance)

In [9]:
# Khai báo một số tham số cố định 
dim = len(X_train[0])
size_X_train = X_train.shape[0]
size_X_test = X_test.shape[0]
size_y_train = y_train.shape[0]
size_y_test = y_test.shape[0]

print("Số chiều của một văn bản là : " + str(dim))
print("Số văn bản train là : " + str(size_X_train))
print("So khớp với y : " + str(size_y_train))
print("Số văn bản test là : " + str(size_X_test))
print("So khớp với y : " + str(size_y_test))

Số chiều của một văn bản là : 100
Số văn bản train là : 58892
So khớp với y : 58892
Số văn bản test là : 25240
So khớp với y : 25240


In [10]:
# Tính xác suất của mỗi nhãn 
prob_label = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
total_label = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
for i in range(0, size_X_train) : 
  total_label[int(y_train[i])] += 1

for i in range(0, 10):
  prob_label[i] = total_label[i] / size_X_train

print(total_label)
print(prob_label)

[3636, 5480, 2741, 5359, 8950, 6730, 6161, 8375, 4929, 6531]
[0.06174013448346125, 0.09305168783535964, 0.04654282415268627, 0.09099707939957889, 0.15197310330774977, 0.11427698159342525, 0.10461522787475379, 0.1422094681790396, 0.08369557834680431, 0.1108979148271412]


In [11]:
# khởi tạo vector giá trị trung bình và độ lệch chuẩn 
Means = np.zeros((10, dim))
Stdevs = np.zeros((10, dim))

In [12]:
print(len(Means[0]))
print(len(Stdevs[0]))

100
100


In [13]:
import math

# Tính giá trị trung binh của mỗi thuôc tính theo từng nhãn 
for i_train in range(0, size_X_train) : 
  label = int(y_train[i_train])
  for i in range(0, dim) : 
    Means[label][i] += X_train[i_train][i] / total_label[label]

# Tính bình phương độ lệch chuẩn trung bình của mỗi thuộc tính theo từng nhãn 
for i_train in range(0, size_X_train) : 
  label = int(y_train[i_train])
  for i in range(0, dim) : 
    avg = Means[label][i]
    Stdevs[label][i] += pow(X_train[i_train][i] - avg, 2) / total_label[label]

# Tính lại độ lệch chuẩn của mỗi thuộc tính theo từng nhãn 
for i in range(0,10) :
  for j in range(0, dim) : 
    Stdevs[i][j] = math.sqrt(Stdevs[i][j])

print(Means)
print(Stdevs)

[[ 5.85535338e-01  1.69325571e+00 -4.49237423e+00  1.63686695e+00
   7.99079537e-01  8.88948763e-01 -2.20037472e+00 -1.13708632e+00
  -1.22107993e+00  6.11369324e+00 -2.70265642e+00  2.14969634e+00
   1.05477337e+00 -6.75121735e+00 -4.64719953e+00  6.95384712e+00
  -2.79358852e+00 -5.12689564e+00  5.26678458e+00 -7.38865088e+00
   5.96382826e+00  1.88636610e+00 -5.49392826e+00 -6.42219976e-01
  -7.81027000e+00 -8.12476850e-01  4.58486585e+00 -2.97350093e+00
   6.46420552e+00 -8.07934398e-01 -1.63497671e+00  1.23130753e+00
   2.39148028e+00 -7.23987614e-01  1.07753795e-02 -6.16496946e+00
  -2.67031833e+00  3.84867547e+00 -4.61278473e+00 -8.19282032e-01
   1.18355891e+00  3.15933373e+00 -3.97335482e+00 -5.34829676e-01
  -1.11913575e+00 -1.36896635e+01 -7.65808430e-03 -9.54503338e+00
   5.19245637e-01 -1.71311300e-01 -2.76515108e+00 -4.21087864e+00
   4.87721817e+00 -8.30866860e+00  3.58127338e+00 -6.99598790e+00
  -2.46604209e+00 -2.94894201e+00  4.83551328e+00 -8.60599907e+00
   9.50354

In [14]:
# Kiểm tra kết quả của Means và Stdevs 
means = np.zeros(dim)
for i_train in range(0, size_X_train) : 
  if int(y_train[i_train]) == 1 : 
    for i in range(0, dim) :
      means[i] += X_train[i_train][i] / total_label[1]

print(means)

[  1.54811215   0.84212753  -0.92732216   0.5881187    0.42686092
  -1.91519627  -1.76354155  -1.18037654  -3.85103119   4.93089794
   0.05395243   5.65283453   1.30713954  -3.9175627   -6.75227269
  -1.90305173  -7.83352158  -4.39769745   8.42221681  -1.18124082
   1.04893967   1.28526246  -0.23990829  -1.85056651  -6.13237922
   4.61272485   5.67280221  -0.8458698   -2.07146313   2.28752009
  -4.60280202   0.51873134   1.35645768   0.86673816  -0.9878061
  -1.86205201  -2.02974427   0.64710361  -4.56439046  -2.85503458
   0.30955356  -2.36512432  -3.34485137  -1.3127168   -0.43210876
 -10.80542969   0.03522785  -6.91744581  -1.54287894   1.65705863
  -1.58195782  -0.85776557   4.70366573   0.56639392   3.94954027
  -4.57391043   0.85701874   1.00563376   4.59002839  -8.23713725
  -1.65973689   2.91247589  -0.39193449  -1.1518732   -2.8265258
   1.33181251  -0.90789983   5.20179075   1.0978723    1.41534841
   1.87441824  -2.50662753  -4.87715943   0.5312581    0.43237665
  -0.4385071

In [15]:
# Hàm tính xác suất theo từng chỉ số 
def pdf(x, mean, sd) : 
  exponent = math.exp(-(math.pow(x - mean, 2) / (2 * math.pow(sd, 2))))
  return (1 / (math.sqrt(2 * math.pi) * sd)) * exponent

# Tính xác suất của mỗi vector theo từng nhãn 
def calc_class_prob(input_vector):
  class_prob = []
  for label in range(0, 10) :
    tmp_prob = 1.0
    for i in range(0, dim) : 
      tmp_prob *= pdf(input_vector[i], Means[label][i], Stdevs[label][i])
    
    class_prob.append(tmp_prob * prob_label[label])
  
  return class_prob

# Dự đoán phân lớp thuộc về của vector đó 
def predict(input_vector) :
  class_prob = calc_class_prob(input_vector)

  max_index = -1
  max_value = 0.0
  for i_prob in range(0,10) : 
    if class_prob[i_prob] > max_value : 
      max_index = i_prob
      max_value = class_prob[i_prob]
  
  return max_index

In [16]:
y_pred = []
for i_test in X_test : 
  i_pred = predict(i_test)
  y_pred.append(i_pred)

In [17]:
matrix = np.zeros((10,10), dtype=int)

cnt = 0
for i in range(0, size_X_test):
  if int(y_pred[i]) == int(y_test[i]) : 
    cnt += 1
  matrix[int(y_test[i])][y_pred[i]] += 1

print("Tỉ lệ chính xác : " + str(cnt / size_X_test) + " %\n" )
print("Ma trận recall và presicion : ")
print(matrix)

Tỉ lệ chính xác : 0.4534469096671949 %

Ma trận recall và presicion : 
[[ 504   11  184  145   40  337   73   16   26  223]
 [ 173  813   12  295   75  820   17    6  128    9]
 [ 145    7  322   35   29  492   43    4   70   28]
 [ 101   51   10 1054  157  879    6    4    9   26]
 [ 329   94  124  775  662 1645   60   36   74   37]
 [  98   10   39   37   89 2572    9    5    2   23]
 [ 272    6  110   96   12  873 1204    2   46   19]
 [ 202    3   10  112   73 1147    2 2006    3   32]
 [ 127   35   11   17   23  471    1    6 1392   29]
 [ 267    8   31  160   33 1230    2   90   52  926]]


# Sử dụng thư viện sklearn kiểm tra kết quả 

In [18]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()  
classifier.fit(X_train, y_train) 

GaussianNB(priors=None, var_smoothing=1e-09)

In [19]:
y_pred = classifier.predict(X_test)  

In [20]:
matrix = np.zeros((10,10), dtype=int)

cnt = 0
for i in range(0, size_X_test):
  if y_pred[i] == int(y_test[i]) : 
    cnt += 1
  matrix[int(y_test[i])][int(y_pred[i])] += 1

print("Tỉ lệ chính xác : " + str(cnt / size_X_test) + " %\n" )
print("Ma trận recall và presicion : ")
print(matrix)

Tỉ lệ chính xác : 0.4540412044374009 %

Ma trận recall và presicion : 
[[ 519   11  184  145   40  337   73   16   26  208]
 [ 178  813   12  295   75  820   17    6  128    4]
 [ 150    7  322   35   29  492   43    4   70   23]
 [ 101   51   10 1054  157  879    6    4    9   26]
 [ 341   94  124  775  662 1645   60   36   74   25]
 [  98   10   39   37   89 2572    9    5    2   23]
 [ 285    6  110   96   12  873 1204    2   46    6]
 [ 204    3   10  112   73 1147    2 2006    3   30]
 [ 138   35   11   17   23  471    1    6 1392   18]
 [ 277    8   31  160   33 1230    2   90   52  916]]
